/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_TICTACTOESERVERSTUB_H_
#define JSONRPC_CPP_STUB_TICTACTOESERVERSTUB_H_

#include <jsonrpccpp/server.h>

class TicTacToeServerStub : public jsonrpc::AbstractServer<TicTacToeServerStub>
{
    public:
        TicTacToeServerStub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<TicTacToeServerStub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("Status.Ping", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &TicTacToeServerStub::Status_PingI);
            this->bindAndAddMethod(jsonrpc::Procedure("TicTacToe.NextMove", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_OBJECT, NULL), &TicTacToeServerStub::TicTacToe_NextMoveI);
            this->bindAndAddMethod(jsonrpc::Procedure("TicTacToe.Complete", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_OBJECT, NULL), &TicTacToeServerStub::TicTacToe_CompleteI);
            this->bindAndAddMethod(jsonrpc::Procedure("TicTacToe.Error", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_OBJECT, NULL), &TicTacToeServerStub::TicTacToe_ErrorI);
        }

        inline virtual void Status_PingI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->Status_Ping();
        }
        inline virtual void TicTacToe_NextMoveI(const Json::Value &request, Json::Value &response)
        {
            response = this->TicTacToe_NextMove(request[0u]);
        }
        inline virtual void TicTacToe_CompleteI(const Json::Value &request, Json::Value &response)
        {
            response = this->TicTacToe_Complete(request[0u]);
        }
        inline virtual void TicTacToe_ErrorI(const Json::Value &request, Json::Value &response)
        {
            response = this->TicTacToe_Error(request[0u]);
        }
        virtual Json::Value Status_Ping() = 0;
        virtual Json::Value TicTacToe_NextMove(const Json::Value& param1) = 0;
        virtual Json::Value TicTacToe_Complete(const Json::Value& param1) = 0;
        virtual Json::Value TicTacToe_Error(const Json::Value& param1) = 0;
};

#endif //JSONRPC_CPP_STUB_TICTACTOESERVERSTUB_H_
